name: Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - '*'

env:
  NEXT_PUBLIC_API_PATH: ${{ secrets.NEXT_PUBLIC_API_PATH }}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.18']
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run lint

  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.18']
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run test:unit:coverage
      - uses: actions/upload-artifact@v3
        with:
          name: coverage_unit
          path: ./.coverage_unit/coverage-final.json
          retention-days: 1

  e2e_test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.18']
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm exec playwright install --with-deps
      - run: pnpm run test:e2e
      - uses: actions/upload-artifact@v3
        with:
          name: coverage_e2e
          path: ./.coverage_e2e/coverage-final.json
          retention-days: 1

  upload_coverage:
    needs: [unit_test, e2e_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Download coverage_unit
        uses: actions/download-artifact@v3
        with:
          name: coverage_unit
      - name: Download coverage_e2e
        uses: actions/download-artifact@v3
        with:
          name: coverage_e2e
      - run: pnpm run coverage-merge
      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./.coverage.json
          flags: unit
